// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQk8GkoBxOH_ekM2bUzn_RNweK67Tz7X8',
    appId: '1:460433524163:web:14b758e8524fc634582976',
    messagingSenderId: '460433524163',
    projectId: 'chatapp-11617',
    authDomain: 'chatapp-11617.firebaseapp.com',
    storageBucket: 'chatapp-11617.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjinrLHliU5ZzEOf60rlHknLw4iXSjZy8',
    appId: '1:460433524163:android:cf54cecbacf28bf1582976',
    messagingSenderId: '460433524163',
    projectId: 'chatapp-11617',
    storageBucket: 'chatapp-11617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjnGGG38lPD0YeyBrx8RSgJ_Pv_QcVH3Y',
    appId: '1:460433524163:ios:105b0f61c7047ce6582976',
    messagingSenderId: '460433524163',
    projectId: 'chatapp-11617',
    storageBucket: 'chatapp-11617.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjnGGG38lPD0YeyBrx8RSgJ_Pv_QcVH3Y',
    appId: '1:460433524163:ios:105b0f61c7047ce6582976',
    messagingSenderId: '460433524163',
    projectId: 'chatapp-11617',
    storageBucket: 'chatapp-11617.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQk8GkoBxOH_ekM2bUzn_RNweK67Tz7X8',
    appId: '1:460433524163:web:b2df0645248eedde582976',
    messagingSenderId: '460433524163',
    projectId: 'chatapp-11617',
    authDomain: 'chatapp-11617.firebaseapp.com',
    storageBucket: 'chatapp-11617.firebasestorage.app',
  );

}